### ISSUE TITLE
Hacer desaparecer el mensaje una vez mostrado

### ISSUE THREAD

**Issue by gabrielcasafu** [JoseJPR/tutorial-navigator-network-connection#1]
Hola Jose! Gracias por compartir el código. Me fue de mucha ayuda. Ahora... propongo...
Una vez que se muestra el mensaje... 
se podría hacer que desapareciera y que no quede fijo?

**Comment by JoseJPR** [comment]
Hola @gabrielcasafu, me alegro que te fuera de ayuda el código 👍 

Sí claro podemos plantear una estrategia de desaparición del banner. ¿Tienes en mente que se pueda tanto si tienes conexión o la recuperas como si la pierdes, osea tanto el banner verde como el rojo?

Quizás podríamos hacer que desaparezca de forma customizada en X milisegundos por ejemplo. ¿Qué te parece?

Saludos!

**Comment by gabrielcasafu** [comment]
Si, estaría bueno que para ambos casos (si se tiene conexión o si se pierde) una vez que se muestra, luego desaparezca. Y me gusta la idea de tomar milisegundos para que suceda.

**Comment by gabrielcasafu** [comment]
Buenos días Jose. Disculpa mi insistencia. ¿Podrías agregar esta
funcionalidad? Necesito agregarlo a un desarrollo y no me doy cuenta de
como hacerlo. Saludos y gracias!

**Comment by JoseJPR** [comment]
@gabrielcasafu siento la demora, mañana podré afrontar el feature. Estos días he tenido un gran volumen de trabajo y no me ha dado tiempo a realizarlo, sorry.

**Comment by JoseJPR** [comment]
@gabrielcasafu Ya tienes una actualización de este tutorial. En este caso para poder personalizar el componente he optado por realizar un refactor y trabajar con clases y métodos con la idea de que a futuro se pueda trabajar de forma más eficiente y ordenada.

El archivo que ha sufrido estos cambios es: https://github.com/JoseJPR/tutorial-navigator-network-connection/blob/master/public/js/app.js

Verás como instanciarlo, mostrar un mensaje personalizado en caso de pérdida de conexión y otro en el caso de recuperarla así como un delay para que el mensaje se oculte de forma automática tras x milisegundos.

**Comment by gabrielcasafu** [comment]
@JoseJPR Excelente! Funcionando a la perfección. Muchísimas gracias por el tremendo aporte.

**Comment by JoseJPR** [comment]
@gabrielcasafu De nada! un placer ayudar 👍
